# Generated by Django 6.0.5 on 2026-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('delivery', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('crops_order', models.TextField(blank=True)),
                ('order_total', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
